[package]
name = "raad-codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0.78"
quote = "1.0.32"
raad = { version = "0.1.2", path = "../raad" }
syn = { version = "2.0.15", features = ["full"] }

[lib]
proc-macro = true
